### ISSUE TITLE
Can't find factory for 'abbreviation_detector' for language English (en)

### ISSUE THREAD

**Issue by qiansehu** [chaoyi-wu/RadFM#32]
Hello, while I try to run the train.py in src, i got this error  :

/root/miniconda3/envs/radfm/lib/python3.9/site-packages/spacy/language.py:2195: FutureWarning: Possible set union at position 6328
  deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(  # type: ignore[union-attr]
Traceback (most recent call last):
  File "/home/test/RadFM/src/train.py", line 129, in <module>
    main()
  File "/home/test/RadFM/src/train.py", line 109, in main
    Train_dataset = multi_dataset(text_tokenizer = model_args.tokenizer_path)
  File "/home/test/RadFM/src/Dataset/multi_dataset.py", line 88, in __init__
    self.words_extract = umls_extractor()
  File "/home/test/RadFM/src/Dataset/multi_dataset.py", line 25, in __init__
    nlp.add_pipe("abbreviation_detector")
  File "/root/miniconda3/envs/radfm/lib/python3.9/site-packages/spacy/language.py", line 821, in add_pipe
    pipe_component = self.create_pipe(
  File "/root/miniconda3/envs/radfm/lib/python3.9/site-packages/spacy/language.py", line 690, in create_pipe
    raise ValueError(err)
ValueError: [E002] Can't find factory for 'abbreviation_detector' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Available factories: attribute_ruler, tok2vec, merge_noun_chunks, merge_entities, merge_subtokens, token_splitter, doc_cleaner, parser, beam_parser, lemmatizer, trainable_lemmatizer, entity_linker, entity_ruler, tagger, morphologizer, ner, beam_ner, senter, sentencizer, spancat, spancat_singlelabel, span_finder, future_entity_ruler, span_ruler, textcat, textcat_multilabel, en.lemmatizer

i had search some issue said build a new env can solve this , but i tried it's not work 

![image](https://github.com/chaoyi-wu/RadFM/assets/68392479/7b6d8d86-2960-4d24-bf29-a5506b4290e0)

**Comment by RobsoUganda** [comment]
Installing things in a new environment solved the issue. As was mentioned  here works [https://github.com/allenai/scispacy/issues/347](url)
