### ISSUE TITLE
Quick_demo does not work

### ISSUE THREAD

**Issue by lukaszbinden** [chaoyi-wu/RadFM#9]
Hi,
thank you all for this awesome work, and also for sharing it!

I tried to run the Quick_demo by following the README instructions:
1) Downloaded the pytorch_model.bin from [1] and placed it in folder Quick_demo/

2) Ran python test.py with a) 4x RTX3090, then b) 8x RTX3090, but got the following error OOM message both times:
Setup tokenizer
Finish loading tokenizer
Setup demo case
Finish loading demo case
Setup Model
Finish loading model
Traceback (most recent call last):
  File "/storage/homefs/lz20w714/git/radfm/Quick_demo/test.py", line 121, in <module>
    main()
  File "/storage/homefs/lz20w714/git/radfm/Quick_demo/test.py", line 105, in main
    model = model.to('cuda')
  File "/storage/homefs/lz20w714/anaconda3/envs/llmood/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/storage/homefs/lz20w714/anaconda3/envs/llmood/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/storage/homefs/lz20w714/anaconda3/envs/llmood/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/storage/homefs/lz20w714/anaconda3/envs/llmood/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/storage/homefs/lz20w714/anaconda3/envs/llmood/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/storage/homefs/lz20w714/anaconda3/envs/llmood/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 100.00 MiB (GPU 0; 23.70 GiB total capacity; 23.39 GiB already allocated; 10.69 MiB free; 23.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Should there be used a quantized version of the model or sth else?

Thanks for your help!

Best,
Lukas

[1] https://huggingface.co/chaoyi-wu/RadFM/blob/main/pytorch_model.zip

**Comment by chaoyi-wu** [comment]
It seems you need to do [Model Parallelism](https://huggingface.co/docs/transformers/v4.15.0/parallelism). Without Model Parallelism, you are actually still work on a single GPU:0, regardless of the practical GPUs you have and considering the model itself will take around 50GB GPU memory, a single RTX3090 can hardly perform forward().

**Comment by thedaffodil** [comment]
Hello, I couldn't run test.py, too.

```python
  model = MultiLLaMAForCausalLM(
        lang_model_path='./Language_files', ### Build up model based on LLaMa-13B config
    )
```  
at this line it gave killed message on terminal.
and my gpu usage doesn't increase while the code was running.

**Comment by chaoyi-wu** [comment]
> Hello, I couldn't run test.py, too.
> 
> ```python
>   model = MultiLLaMAForCausalLM(
>         lang_model_path='./Language_files', ### Build up model based on LLaMa-13B config
>     )
> ```
> 
> at this line it gave killed message on terminal. and my gpu usage doesn't increase while the code was running.

This step will initialize the model in CPU and then the model will be moved to GPU through ```model.to('cuda')```. 

So if you have problem in this step, you may have to check your CPU mem is also large enough for a model larger than 50GB.

**Comment by thedaffodil** [comment]
okay thank you. Is there any way to move this step to GPU?

**Comment by chaoyi-wu** [comment]
You may check this [Sample](https://github.com/chaoyi-wu/Finetune_LLAMA/blob/a5803d401ebbd3520fce57163666a52e6ab31f27/finetune_pp_peft.py#L106) and modify the ```device_map``` as your demand.

**Comment by peiqi-sui** [comment]
Where should the device_map be inserted? I tried 1) adding it as an argument to the MultiLlaMAforCausalLM class and 2) modifying the LlamaForCausalLM.from_pretrained() initialization in multimodality_model.py, but neither utilizes my 2rd GPU. The VRAM of my GPU:0 (48GB) is not enough to run RadFM. Is there another fix to this?

**Comment by Hamesen** [comment]
> Where should the device_map be inserted? I tried 1) adding it as an argument to the MultiLlaMAforCausalLM class and 2) modifying the LlamaForCausalLM.from_pretrained() initialization in multimodality_model.py, but neither utilizes my 2rd GPU. The VRAM of my GPU:0 (48GB) is not enough to run RadFM. Is there another fix to this?

@peiqi-sui Hello, I have also encountered this problem. Have you solved it? I'd like to know how you train with multiple GPUs?

**Comment by Hamesen** [comment]
> okay thank you. Is there any way to move this step to GPU?

@chaoyi-wu @thedaffodil @peiqi-sui @xiaoman-zhang @lukaszbinden Hello, how do you perform multi-GPU training? When I was training, I only used GPU0, while the other GPUs were always idle. Is there any way to train on multiple GPUs at the same time?
